---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.1.1

platforms:
  - name: centos-6.5
    driver_config:
      forward:
      - 80:80

suites:
  - name: default
    run_list:
      - recipe[sample-app::default]
    attributes:
